on:
  push:
    tags: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependency OS packages
        run: sudo apt-get install --no-install-recommends -y upx python3 python3-pytest python3-yaml iproute2 openssl python3-scapy tcpdump
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true
      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v2
        with:
          path: |
            C:/Program Files/LLVM
            ./llvm
          key: llvm-10
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "10"
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build everything for release
        run: ./build.py --compress --lipo --docker --docker-tag-latest --docker-push
      - name: Run tests
        run: sudo python3 -m pytest ./tests
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
